#!/usr/bin/env bash
# script configures nginx to listen to port 80

# remove default nginx configuration file
rm /etc/nginx/sites-enabled/default

# configure nginx to listen to port 80 for all IPv4 IPs
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx
sudo service restart nginx
